namespace RollingDice
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        private void RollButton_Click(object sender, EventArgs e)
        {
            // Create 2 dice objects with randome # of sides (4-20)
            Random random = new Random();
            int sides = random.Next(4,21);
            Dice dice1 = new Dice(sides);
            Dice dice2 = new Dice(sides);
            //face is the face number of the Die generated by rollDie
            int face1 = 0;
            int face2 = 0;
            int rolls = 0;
            //While loop will contisnue to roll until snake eyes appear
            while (( face1 != 1 ) || ( face2 != 1 ))
            {
                face1 = dice1.rollDie();
                face2 = dice2.rollDie();
                rolls++;
                dice1Label.Text = face1.ToString();
                dice2Label.Text = face2.ToString();
            }
            MessageBox.Show("Took " + rolls.ToString() + " rolls to get snake eyes!");
            this.Close();
        }

    }
}